# Generated by Django 5.2.4 on 2025-07-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0002_alter_painting_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='is_sold',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='painting',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='painting',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
