# Generated by Django 5.2.4 on 2025-07-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0003_painting_is_sold_painting_price_alter_painting_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='painting',
            old_name='is_sold',
            new_name='staus',
        ),
        migrations.AddField(
            model_name='painting',
            name='size',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='painting',
            name='year',
            field=models.IntegerField(default=1400),
            preserve_default=False,
        ),
    ]
