# Generated by Django 5.2.4 on 2025-07-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0004_rename_is_sold_painting_staus_painting_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='size',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='painting',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
