# Generated by Django 5.2.4 on 2025-07-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0005_alter_painting_size_alter_painting_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='year',
            field=models.IntegerField(default=1400),
            preserve_default=False,
        ),
    ]
