# Generated by Django 5.2.4 on 2025-07-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0006_alter_painting_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='size',
            field=models.CharField(default=1500, max_length=10),
            preserve_default=False,
        ),
    ]
