# Generated by Django 5.2.4 on 2025-08-02 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0007_alter_painting_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='painting',
            name='material',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='painting',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='painting',
            name='staus',
            field=models.BooleanField(default=True),
        ),
    ]
