# Generated by Django 5.2.4 on 2025-08-05 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0009_painting_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting',
            name='liked_by',
        ),
    ]
