# Generated by Django 5.2.4 on 2025-08-09 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0011_painting_liked_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='painting',
            old_name='staus',
            new_name='status',
        ),
    ]
