# Generated by Django 5.2.4 on 2025-08-10 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0012_rename_staus_painting_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='painting',
            old_name='status',
            new_name='availability',
        ),
    ]
