# Generated by Django 5.2.4 on 2025-08-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0014_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price_snapshot',
            field=models.IntegerField(max_length=12),
        ),
    ]
