# Generated by Django 5.2.4 on 2025-08-05 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0010_remove_painting_liked_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='liked_by',
            field=models.ManyToManyField(blank=True, null=django.db.models.deletion.CASCADE, related_name='liked_paintings', to=settings.AUTH_USER_MODEL),
            preserve_default=django.db.models.deletion.CASCADE,
        ),
    ]
